first-version
FWdarling/DesignPattern pull request #4
Opened 2020-11-12 15:40 UTC by CindyCindy424

## Submit 1
Finish a simple version of patterns below:
Visitor / Prototype / Interpreter / DoubleCheckedLocking

2020-11-13 03:03 UTC, FWdarling requested changes
所有包名应该用小写， 代码结构需要改善（详见comments）

2020-11-13 03:03 UTC, FWdarling commented on src/main/java/Visitor/Visitor.java
> +    double ofShape(Triangle triangle);
- 方法名有没有更好的选择？有一点表意不明， 如果没有的话建议加注释

- 用多态方法尽量加注释解释区别或用途

2020-11-14 10:02 UTC, CindyCindy424 commented on src/main/java/Interpreter/Expression.java
> +    double interpret();
好滴 不过接口的方法默认都是public abstract的嘛 所以就没写

2020-11-14 10:02 UTC, CindyCindy424 commented on src/main/java/Interpreter/MatchException.java
> +        super(msg);
这里本来是想用一个新的MatchException表示一种特定的异常类型，不过要这么说也有点道理hhh  所以我改成了println的形式说明具体的异常类型，这样ok嘛

2020-11-14 10:02 UTC, CindyCindy424 commented on src/main/java/Prototype/entity/Athlete.java
> +    protected final AnimalType animalType;
我当时只是想完善这里角色作为动物的属性（挠头hh，不过开会的时候说的运动员和动物分开为两个单独的体系也可以的

2020-11-14 10:02 UTC, CindyCindy424 commented on src/main/java/Visitor/Visitor.java
> +    double ofShape(Triangle triangle);
认真思考了一下可能这个例子不是特别合适，我先按照要求改了原来的代码，我下来再想想适合的例子把这个设计模式改改

2020-11-14 10:06 UTC, CindyCindy424 commented
包名的大小写我这里该过了，但是github文件里的文件夹名字好像还是改不了... 文件里的`package main.interpreter`倒是改过来了

2020-11-14 18:36 UTC, FWdarling commented
你需要把你的本地包改成小写， 然后commit 和push(你这样只改内部引用不改包名应该是过不了编译的
以及你的source路径和test路径是不是设置的有问题？ source路径为main/java, test路径为test/java， package应该从这个路径下开始计算（比如visitor就是package visitor;而不是main.visitor

2020-11-15 16:27 UTC, CindyCindy424 commented
关于文件名大写的问题，我在本地修改文件夹名字为小写，push到自己的仓库内仍然文件夹为大写；查询资料后，设置git配置改为大小写敏感，但push后原来的大写文件夹没有被覆盖，因此大量执行了删除操作，不知道会不会影响主分支......
【github 大小写问题参考方式：https://www.dazhuanlan.com/2019/10/17/5da7d7867bf31/】

2020-11-16 06:43 UTC, merged