FirstCommit
FWdarling/DesignPattern pull request #9
Opened 2020-11-13 08:37 UTC by MatrixTZuZT

First commit for design pattern of businessdelegate, mediator, decorator

2020-11-15 18:57 UTC, FWdarling requested changes
- 不要把DS_store传到github里, 你可以选择放到gitignore里

- 提一个项目外的建议 大括号内多用空行来划分结构

- oop相关的概念在代码中很多地方没有体现， 详情见comments

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/businessDelegate/Dog.java
> +public class Dog extends Animal {
只有一个dog继承的animal是否能起到测试的作用， 以及是否有继承的必要？

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/businessDelegate/Entity/Animal.java
> +public abstract class Animal {
写一个空的父类用于继承存在的必要性

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/businessDelegate/Dog.java
> +    private QueryDelegate _queryDelegate;
类型和变量如果不能直观的表达出意思， 用注释注明用途或意义

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/decorator/FacebookInformationSender.java
> +    public void sendInformation(String message) {
代码并不直观达意， 建议添加注释说明

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/decorator/InformationSender.java
> +public abstract class InformationSender {
只有一个抽象方法的父类应该声明为接口而非抽象类

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/decorator/InformationSenderForTennis.java
> +        int messageLength = message.length();
建议把格式化的部分单独开一个函数并注明用途，现在这样堆叠在这里有点难理解

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/decorator/TwitterInformationSender.java
> +        int messageLength = message.length();
同上两个文件所述

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/mediator/AbstractTennisCourt.java
> +public abstract class AbstractTennisCourt {
只有抽象方法没有成员的父类应该声明为接口

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/mediator/DispatchMediator.java
> +        switch (info.charAt(0)) {
加注释或用全称来说明不同分支的进入点

2020-11-15 18:57 UTC, FWdarling commented on src/main/java/mediator/TennisCourt01.java
> +public class TennisCourt01 extends AbstractTennisCourt{
是否弄混了继承和实例化的概念？三个tenniscourt完全相同， 应该设计为一个类的三个实例， 通过字符串拼接来做到不同的输出

2020-11-15 18:57 UTC, FWdarling commented on src/test/java/mediator/MediatorTest.java
> +        TennisCourt01 tennisCourt01 = new TennisCourt01(dispatchMediator);
详情见TennisCourt01的comment

2020-11-16 12:09 UTC, MatrixTZuZT commented on src/main/java/mediator/TennisCourt01.java
> +public class TennisCourt01 extends AbstractTennisCourt{
这里我想表达的意思是不同的物体通过中介者来执行交互，他们可以有不同的方法，但这里我就实现了他们共有的方法，我改一下这几个类的种类？

2020-11-16 13:13 UTC, FWdarling commented on src/main/java/mediator/TennisCourt01.java
> +public class TennisCourt01 extends AbstractTennisCourt{
至少目前写的三个类内的方法以及成员完全是一个类， 而且命名上也不像是不同类， 更像是实例， 如果你想表达不同的类可能要重新设计一下

2020-11-17 03:50 UTC, MatrixTZuZT commented on src/main/java/mediator/TennisCourt01.java
> +public class TennisCourt01 extends AbstractTennisCourt{
好的 那我更改一下命名和方法

2020-11-17 04:35 UTC, merged